### ISSUE TITLE
No compatible GPU found

### ISSUE THREAD

**Issue by mentalitycz** [vertcoin-project/one-click-miner-vnext#7]
Fing my GPU

![image](https://user-images.githubusercontent.com/52524601/60646353-75e96580-9e3b-11e9-9b1d-3637549c8ef6.png)

Everytime

alpha14

Win 10
Intel C i7 
16g ram
NVIDIA GeForce 930MX

2019/07/04 09:03:08.464700 [DEBUG] Unmatched GPU: [NVIDIA GeForce 930MX]
2019/07/04 09:03:08.523539 [DEBUG] Unmatched GPU: [Intel(R) UHD Graphics 620]
2019/07/04 09:03:08.645726 [INFO] Checking wallet..
2019/07/04 09:03:08.647722 [INFO] Initializing wallet VagCEy9Fax4PeNnTNZiwBzzC5vernujDwD
2019/07/04 09:03:08.648722 [INFO] Wallet initialized: 1
2019/07/04 09:03:22.033751 [INFO] Stopping mining process...
2019/07/04 09:09:25.104833 [DEBUG] Unmatched GPU: [NVIDIA GeForce 930MX]
2019/07/04 09:09:25.154699 [DEBUG] Unmatched GPU: [Intel(R) UHD Graphics 620]
2019/07/04 09:09:26.647471 [INFO] Checking wallet..
2019/07/04 09:09:26.648468 [INFO] Initializing wallet VagCEy9Fax4PeNnTNZiwBzzC5vernujDwD
2019/07/04 09:09:26.648468 [INFO] Wallet initialized: 1

**Comment by mentalitycz** [comment]
also tested w alpha15, same issue

**Comment by gertjaap** [comment]
Fixed in Alpha 16

**Comment by mentalitycz** [comment]
MAybe were not clear...the showing version is working...but GPU still not recognized
![image](https://user-images.githubusercontent.com/52524601/60653233-f1521380-9e49-11e9-8a31-22e4ecdc0b39.png)

**Comment by mentalitycz** [comment]
019/07/04 10:52:52.084806 [INFO] Checking wallet..
2019/07/04 10:52:52.142652 [INFO] Initializing wallet VagCEy9Fax4PeNnTNZiwBzzC5vernujDwD
2019/07/04 10:52:52.143650 [INFO] Wallet initialized: 1
2019/07/04 10:52:52.703154 [DEBUG] Unmatched GPU: [NVIDIA GeForce 930MX]
2019/07/04 10:52:52.703154 [DEBUG] Unmatched GPU: [Intel(R) UHD Graphics 620]
